name: Deploy to Github Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
permissions:
  contents: write
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 3.2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.306'
                   
                 
     

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish ./ElwaldeEquipment/ElwaldeEquipment.csproj -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'ElwaldeEquipment' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to ElwaldeEquipment
      run: sed -i 's/<base href="\/" \/>/<base href="\/ElwaldeEquipment\/" \/>/g' release/wwwroot/index.html
    
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
